"""
File: streamlit_app/app.py
Author: Santiago (initial landing-zone tile + streaming tile) + Albert (full lakehouse view)
Created: 2026-05-11
Updated: 2026-06-01

Pipeline Stage: Consumption / BI seam

Description
-----------
Single-page Streamlit dashboard that surfaces all four zones of the lakehouse:

  1. Landing Zone  — raw objects in MinIO (P1 cold path)
  2. Trusted Zone  — typed, deduped tables in duckdb/trusted.duckdb
  3. Exploitation  — star schema + streaming view in duckdb/exploit.duckdb
  4. Streaming     — live 1-minute character-mention aggregates (parquet)
  5. Milvus        — corpus_chunks vector collection stats
  6. Consumption   — latest podcast episodes generated by the agent stack

Each tab is independent and degrades gracefully if its source isn't populated
yet (e.g. before the Airflow DAGs run, before the streaming job starts).
"""

import glob
import os
from pathlib import Path

import boto3
import pandas as pd
import streamlit as st
from botocore.client import Config

# ─── Configuration ────────────────────────────────────────────────────────────
st.set_page_config(page_title="BDM Lakehouse Dashboard", layout="wide")

MINIO_ENDPOINT = os.getenv("MINIO_ENDPOINT", "http://minio:9000")
MINIO_ACCESS_KEY = os.getenv("MINIO_ACCESS_KEY", "admin")
MINIO_SECRET_KEY = os.getenv("MINIO_SECRET_KEY", "password")
MINIO_BUCKET = os.getenv("MINIO_BUCKET", "landing-zone")

DUCKDB_DIR = Path(os.getenv("DUCKDB_DIR", "/opt/airflow/duckdb"))
TRUSTED_DB = DUCKDB_DIR / "trusted.duckdb"
EXPLOIT_DB = DUCKDB_DIR / "exploit.duckdb"

STREAMING_PATH = Path(os.getenv(
    "STREAM_OUTPUT_PATH",
    "/opt/airflow/streaming/fact_mentions_1m",
))

EPISODES_DIR = Path(os.getenv(
    "EPISODES_DIR",
    "/opt/airflow/consumption/episodes",
))

MILVUS_HOST = os.getenv("MILVUS_HOST", "milvus")
MILVUS_PORT = int(os.getenv("MILVUS_PORT", "19530"))

# ─── Header ───────────────────────────────────────────────────────────────────
st.title("BDM Lakehouse — Historical Conversational AI")
st.caption(
    "Landing → Trusted → Exploitation → Consumption. "
    "Each tab inspects a single zone independently."
)

with st.sidebar:
    st.header("Connections")
    st.write(f"**MinIO bucket:** `{MINIO_BUCKET}`")
    st.write(f"**MinIO endpoint:** `{MINIO_ENDPOINT}`")
    st.write(f"**DuckDB dir:** `{DUCKDB_DIR}`")
    st.write(f"**Streaming path:** `{STREAMING_PATH}`")
    st.write(f"**Milvus:** `{MILVUS_HOST}:{MILVUS_PORT}`")

tab_landing, tab_trusted, tab_exploit, tab_stream, tab_milvus, tab_episodes = st.tabs(
    [
        "Landing",
        "Trusted",
        "Exploitation",
        "Streaming",
        "Milvus",
        "Episodes",
    ]
)

# ─── Tab 1: Landing Zone (MinIO objects) ──────────────────────────────────────
with tab_landing:
    st.subheader("Landing Zone — Raw objects in MinIO")
    s3 = boto3.client(
        "s3",
        endpoint_url=MINIO_ENDPOINT,
        aws_access_key_id=MINIO_ACCESS_KEY,
        aws_secret_access_key=MINIO_SECRET_KEY,
        config=Config(signature_version="s3v4"),
        region_name="us-east-1",
    )

    try:
        paginator = s3.get_paginator("list_objects_v2")
        objects = []
        for page in paginator.paginate(Bucket=MINIO_BUCKET):
            objects.extend(page.get("Contents", []))

        if not objects:
            st.warning("No files found yet. Run the Airflow ingestion DAG first.")
        else:
            df = pd.DataFrame(objects)
            df["Size_MB"] = df["Size"] / (1024 * 1024)
            df["Source"] = df["Key"].apply(lambda x: x.split("/")[0])

            c1, c2, c3 = st.columns(3)
            c1.metric("Files", f"{len(df):,}")
            c2.metric("Total MB", f"{df['Size_MB'].sum():.1f}")
            c3.metric("Sources", df["Source"].nunique())

            st.subheader("Files by Source")
            st.bar_chart(df.groupby("Source").size().rename("Files"))

            with st.expander(f"Browse {len(df):,} objects"):
                st.dataframe(
                    df[["Key", "Size_MB", "LastModified"]],
                    use_container_width=True,
                )
    except Exception as e:
        st.error("Could not connect to MinIO.")
        st.exception(e)

# ─── DuckDB helpers ───────────────────────────────────────────────────────────
def open_duckdb(path: Path):
    if not path.exists():
        return None
    try:
        import duckdb
    except ImportError:
        st.error("duckdb not installed in the Streamlit env.")
        return None
    return duckdb.connect(str(path), read_only=True)

def list_tables(con) -> pd.DataFrame:
    return con.execute(
        """
        SELECT table_name
        FROM information_schema.tables
        WHERE table_schema = 'main'
        ORDER BY table_name
        """
    ).fetch_df()

# ─── Tab 2: Trusted Zone ──────────────────────────────────────────────────────
with tab_trusted:
    st.subheader("Trusted Zone — typed, deduped tables")
    con = open_duckdb(TRUSTED_DB)
    if con is None:
        st.warning(
            f"`{TRUSTED_DB}` not found yet. "
            "Run the `bdm_p2_trusted_zone_dag` Airflow DAG."
        )
    else:
        tables = list_tables(con)
        if tables.empty:
            st.info("No tables yet — the trusted DAG hasn't populated this database.")
        else:
            rows = []
            for t in tables["table_name"]:
                n = con.execute(f"SELECT COUNT(*) FROM {t}").fetchone()[0]
                rows.append({"table": t, "rows": n})
            counts = pd.DataFrame(rows)

            c1, c2 = st.columns(2)
            c1.metric("Tables", len(counts))
            c2.metric("Total rows", f"{counts['rows'].sum():,}")
            st.bar_chart(counts.set_index("table")["rows"])
            st.dataframe(counts, use_container_width=True)

            with st.expander("Peek at a table"):
                pick = st.selectbox("Table", counts["table"].tolist())
                st.dataframe(
                    con.execute(f"SELECT * FROM {pick} LIMIT 50").fetch_df(),
                    use_container_width=True,
                )
        con.close()

# ─── Tab 3: Exploitation Zone (star schema) ───────────────────────────────────
with tab_exploit:
    st.subheader("Exploitation Zone — star schema")
    con = open_duckdb(EXPLOIT_DB)
    if con is None:
        st.warning(
            f"`{EXPLOIT_DB}` not found yet. "
            "Run the `bdm_p2_exploitation_zone_dag` Airflow DAG."
        )
    else:
        tables = list_tables(con)
        if tables.empty:
            st.info("No tables yet — the exploitation DAG hasn't populated this database.")
        else:
            counts = pd.DataFrame(
                [
                    {
                        "table": t,
                        "rows": con.execute(f"SELECT COUNT(*) FROM {t}").fetchone()[0],
                    }
                    for t in tables["table_name"]
                ]
            )
            c1, c2 = st.columns(2)
            c1.metric("Tables / views", len(counts))
            c2.metric("Total rows", f"{counts['rows'].sum():,}")
            st.dataframe(counts, use_container_width=True)

            st.markdown("---")
            st.markdown("### Quick star-schema queries")

            if "dim_figure" in counts["table"].values:
                st.markdown("### Figure cards (`dim_figure`)")
                st.caption(
                    "Every column we ingested for each of the 9 figures — "
                    "portrait, era, school/interests, Wikipedia/SEP/IEP links."
                )
                figs = con.execute(
                    """
                    SELECT figure_slug, name, domain, school, born, died,
                           interests, wikipedia_description, wikipedia_summary,
                           wikipedia_link, sep_link, iep_link, thumbnail_url
                    FROM dim_figure ORDER BY domain, name
                    """
                ).fetch_df()

                def _era(born, died):
                    def fmt(y):
                        if y is None or pd.isna(y):
                            return "?"
                        y = int(y)
                        return f"{-y} BC" if y < 0 else str(y)
                    span = (
                        int(died) - int(born)
                        if pd.notna(born) and pd.notna(died) else None
                    )
                    line = f"{fmt(born)} – {fmt(died)}"
                    if span is not None:
                        line += f"  ({span} yrs)"
                    return line

                # 3 columns × 3 rows
                cols = st.columns(3)
                for i, row in figs.iterrows():
                    with cols[i % 3]:
                        with st.container(border=True):
                            inner = st.columns([1, 2])
                            with inner[0]:
                                if row["thumbnail_url"]:
                                    st.image(row["thumbnail_url"], width=110)
                            with inner[1]:
                                st.markdown(f"**{row['name']}**")
                                st.caption(
                                    f"_{row['wikipedia_description'] or row['domain']}_"
                                )
                                st.caption(_era(row["born"], row["died"]))
                                if row["school"]:
                                    st.caption(f"School: {row['school']}")
                            summ = row["wikipedia_summary"] or ""
                            if summ:
                                st.markdown(
                                    summ[:280] + ("…" if len(summ) > 280 else "")
                                )
                            link_bits = []
                            if row["wikipedia_link"]:
                                link_bits.append(f"[Wikipedia]({row['wikipedia_link']})")
                            if row["sep_link"]:
                                link_bits.append(f"[SEP]({row['sep_link']})")
                            if row["iep_link"]:
                                link_bits.append(f"[IEP]({row['iep_link']})")
                            if link_bits:
                                st.caption(" · ".join(link_bits))
                st.markdown("---")

            cols = st.columns(2)

            if "fact_quotes" in counts["table"].values:
                with cols[0]:
                    st.markdown("**Top quoted figures (`fact_quotes`)**")
                    df = con.execute(
                        """
                        SELECT figure_slug, COUNT(*) AS quotes
                        FROM fact_quotes
                        GROUP BY figure_slug
                        ORDER BY quotes DESC
                        LIMIT 10
                        """
                    ).fetch_df()
                    st.bar_chart(df.set_index("figure_slug"))

            if "fact_works" in counts["table"].values:
                with cols[1]:
                    st.markdown("**Gutenberg works per figure (`fact_works`)**")
                    df = con.execute(
                        """
                        SELECT figure_slug, COUNT(*) AS works
                        FROM fact_works
                        GROUP BY figure_slug
                        ORDER BY works DESC
                        """
                    ).fetch_df()
                    st.bar_chart(df.set_index("figure_slug"))

            if "fact_news_articles" in counts["table"].values:
                st.markdown("**News articles by category (`fact_news_articles`)**")
                df = con.execute(
                    """
                    SELECT category, COUNT(*) AS articles
                    FROM fact_news_articles
                    GROUP BY category
                    ORDER BY articles DESC
                    """
                ).fetch_df()
                st.bar_chart(df.set_index("category"))

            if "fact_se_qa" in counts["table"].values:
                st.markdown("**Stack Exchange Q&A — top mentioned figures (`fact_se_qa`)**")
                try:
                    df = con.execute(
                        """
                        SELECT figure_slug, COUNT(*) AS qa_pairs
                        FROM (
                            SELECT UNNEST(mentioned_figures) AS figure_slug
                            FROM fact_se_qa
                            WHERE mentioned_figures IS NOT NULL
                        )
                        GROUP BY figure_slug
                        ORDER BY qa_pairs DESC
                        """
                    ).fetch_df()
                    st.dataframe(df, use_container_width=True)
                except Exception as e:
                    st.caption(f"SE panel skipped ({e}).")

            if "fact_mentions_1m" in counts["table"].values:
                st.markdown("**Live streaming mentions (`fact_mentions_1m` view)**")
                try:
                    df = con.execute(
                        """
                        SELECT figure_slug, character_name,
                               SUM(mention_count) AS mentions,
                               AVG(avg_sentiment)  AS sentiment
                        FROM fact_mentions_1m
                        GROUP BY figure_slug, character_name
                        ORDER BY mentions DESC
                        """
                    ).fetch_df()
                    st.dataframe(df, use_container_width=True)
                except Exception as e:
                    st.caption(f"View registered but no streaming data yet ({e}).")

            if "fact_hn_stories" in counts["table"].values:
                st.markdown("**Hacker News discourse signal (`fact_hn_stories`)**")
                hcols = st.columns(2)
                with hcols[0]:
                    st.caption("Stories per figure")
                    df = con.execute(
                        """
                        SELECT figure_slug, COUNT(*) AS stories
                        FROM fact_hn_stories
                        GROUP BY figure_slug
                        ORDER BY stories DESC
                        """
                    ).fetch_df()
                    st.bar_chart(df.set_index("figure_slug"))
                with hcols[1]:
                    st.caption("Top hosts (all figures)")
                    df = con.execute(
                        """
                        SELECT host, COUNT(*) AS stories
                        FROM fact_hn_stories
                        WHERE host IS NOT NULL
                        GROUP BY host
                        ORDER BY stories DESC
                        LIMIT 15
                        """
                    ).fetch_df()
                    st.bar_chart(df.set_index("host"))

                st.caption("Top stories (highest points first)")
                df = con.execute(
                    """
                    SELECT figure_slug, host, points, num_comments,
                           title, url
                    FROM fact_hn_stories
                    ORDER BY points DESC NULLS LAST
                    LIMIT 25
                    """
                ).fetch_df()
                st.dataframe(df, use_container_width=True)

            with st.expander("Custom SQL"):
                q = st.text_area("Query", "SELECT * FROM dim_figure LIMIT 10")
                if st.button("Run"):
                    try:
                        st.dataframe(con.execute(q).fetch_df(), use_container_width=True)
                    except Exception as e:
                        st.error(str(e))
        con.close()

# ─── Tab 4: Streaming ─────────────────────────────────────────────────────────
with tab_stream:
    st.subheader("Streaming Zone — 1-minute character mention aggregates")
    parquet_files = glob.glob(f"{STREAMING_PATH}/*.parquet")
    if not parquet_files:
        st.warning(
            f"No streaming parquet files under `{STREAMING_PATH}` yet. "
            "Start `stream_producer.py` and `spark_stream_mentions_1m.py`."
        )
    else:
        df = pd.read_parquet(STREAMING_PATH)
        c1, c2, c3 = st.columns(3)
        c1.metric("Window rows", f"{len(df):,}")
        c2.metric("Characters", df["character_name"].nunique())
        c3.metric("Latest window", str(df["window_end"].max()))

        st.subheader("Total mentions by character")
        st.bar_chart(
            df.groupby("character_name")["mention_count"]
              .sum()
              .sort_values(ascending=False)
        )

        st.subheader("Average sentiment by domain")
        st.bar_chart(df.groupby("domain")["avg_sentiment"].mean())

        with st.expander(f"All {len(df):,} window rows"):
            st.dataframe(
                df.sort_values("window_end", ascending=False),
                use_container_width=True,
            )

# ─── Tab 5: Milvus (vector store) ─────────────────────────────────────────────
with tab_milvus:
    st.subheader("Milvus — `corpus_chunks` collection")
    try:
        from pymilvus import connections, utility, Collection
        connections.connect(alias="dash", host=MILVUS_HOST, port=MILVUS_PORT)
        if not utility.has_collection("corpus_chunks", using="dash"):
            st.warning(
                "`corpus_chunks` collection not found. "
                "Run `exploitation/structured/corpus_chunks.py`."
            )
        else:
            col = Collection("corpus_chunks", using="dash")
            col.load()
            c1, c2 = st.columns(2)
            c1.metric("Total chunks", f"{col.num_entities:,}")
            c2.metric("Embedding dim", 384)
            st.caption("Index: HNSW (M=16, efConstruction=200), metric=COSINE.")
            st.caption("Embedder: sentence-transformers/all-MiniLM-L6-v2.")

            st.markdown("---")
            st.markdown("### Semantic-search playground")
            st.caption(
                "The same retrieval the Reasoner agent uses. Pick a figure, "
                "type a query, get the top passages from their books / "
                "Wikipedia / Wikiquote / SE — ranked by cosine similarity."
            )

            # Pull the figure list from exploit.duckdb for the dropdown.
            figure_choices: list[str] = []
            if EXPLOIT_DB.exists():
                fcon = open_duckdb(EXPLOIT_DB)
                if fcon is not None:
                    try:
                        figure_choices = [
                            r[0] for r in fcon.execute(
                                "SELECT figure_slug FROM dim_figure ORDER BY name"
                            ).fetchall()
                        ]
                    finally:
                        fcon.close()

            sc1, sc2, sc3 = st.columns([1, 3, 1])
            with sc1:
                fig_pick = st.selectbox(
                    "Figure", figure_choices or ["(no figures yet)"],
                    key="milvus_search_figure",
                )
            with sc2:
                query = st.text_input(
                    "Query",
                    value="What can we know about reality?",
                    key="milvus_search_query",
                )
            with sc3:
                top_k = st.number_input(
                    "Top K", min_value=1, max_value=20, value=5,
                    key="milvus_search_topk",
                )

            if st.button("Search", key="milvus_search_btn") and figure_choices:
                try:
                    from sentence_transformers import SentenceTransformer
                    embedder = SentenceTransformer(
                        "sentence-transformers/all-MiniLM-L6-v2"
                    )
                    vec = embedder.encode(
                        [query], normalize_embeddings=True
                    )[0].tolist()
                    expr = f'figure_slug == "{fig_pick}"'
                    res = col.search(
                        [vec], "embedding",
                        {"metric_type": "COSINE", "params": {"ef": 64}},
                        limit=int(top_k), expr=expr,
                        output_fields=["chunk_text", "source", "source_id", "subtype"],
                    )
                    hits = res[0]
                    if not hits:
                        st.info(
                            f"No chunks for `{fig_pick}` matched. "
                            "Try a different figure or query."
                        )
                    for i, hit in enumerate(hits):
                        e = hit.entity
                        src = e.get("source") or ""
                        sid = str(e.get("source_id") or "")
                        sub = e.get("subtype") or ""
                        score = float(hit.distance)
                        with st.container(border=True):
                            st.caption(
                                f"**[{i+1}]** `{src}:{sid}"
                                f"{'/' + sub if sub else ''}` · "
                                f"cosine = {score:.3f}"
                            )
                            st.write(e.get("chunk_text"))
                except ImportError:
                    st.error(
                        "sentence-transformers not installed in the Streamlit "
                        "env. Add it to streamlit_app/requirements.txt."
                    )
                except Exception as e:
                    st.error("Search failed.")
                    st.exception(e)
        connections.disconnect("dash")
    except ImportError:
        st.info("pymilvus not installed in this env — skipping Milvus panel.")
    except Exception as e:
        st.error("Could not query Milvus.")
        st.exception(e)

# ─── Tab 6: Consumption (episodes) ────────────────────────────────────────────
with tab_episodes:
    st.subheader("Consumption Zone — generated podcast episodes")
    if not EPISODES_DIR.exists():
        st.warning(f"`{EPISODES_DIR}` not found.")
    else:
        md_files = sorted(EPISODES_DIR.glob("*.md"), reverse=True)
        if not md_files:
            st.info("No episodes yet. Run `consumption/episode.py`.")
        else:
            st.metric("Episodes", len(md_files))
            choice = st.selectbox(
                "Pick an episode",
                [p.name for p in md_files],
            )
            picked = EPISODES_DIR / choice
            st.markdown(picked.read_text())
