"""
consumption/agents/episode.py
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Consumption Zone — Episode composer

The final consumption artifact. Stitches the three agents into one
host-interview podcast episode for a single figure, topic driven by recent
news:

    [COLD OPEN]  a real by_figure Wikiquote line as the hook
    [HOST INTRO] Interviewer frames the news topic
    [BODY]       per question:  Interviewer asks → figure answers
                 (Reasoner-grounded, Voice-styled, generated by Claude)
    [CLOSE]      host sign-off

Writes two files to consumption/episodes/:
  • <slug>_<stamp>.json  — structured (for the dashboard / programmatic use)
  • <slug>_<stamp>.md    — readable transcript (the demo artifact)

Offline (no llm_fn) it still produces the full structure with answer slots
marked as runtime-generated, so the episode shape is reviewable without an
API key.

CLI:
    python -m consumption.agents.episode --figure kant --live
    python -m consumption.agents.episode --figure darwin --questions 4 --live
"""
from __future__ import annotations

import argparse
import json
import os
from datetime import datetime
from pathlib import Path
from typing import Callable, Optional

from consumption.agents.interviewer import follow_up_question, pick_topic
from consumption.agents.reasoner import load_identity_card, retrieve
from consumption.agents.voice import voiced_answer

ROOT     = Path(__file__).resolve().parents[2]
EPISODES = Path(os.getenv("EPISODES_DIR", ROOT / "consumption" / "episodes"))


def _cold_open(figure_slug: str, theme: str) -> Optional[str]:
    """A punchy quote in the figure's own voice, drawn against the curated
    THEME (intellectual) — never raw news — so the hook stays on substance."""
    hits = retrieve(figure_slug, theme, top_k=1,
                    sources=["wikiquote"], subtype="by_figure")
    return hits[0].text.strip() if hits else None


def build_episode(figure_slug: str,
                  llm_fn: Optional[Callable[[str], str]] = None,
                  n_questions: int = 3) -> dict:
    card  = load_identity_card(figure_slug)
    topic = pick_topic(figure_slug, llm_fn=llm_fn, n_questions=n_questions)
    cold  = _cold_open(figure_slug, topic.theme)

    turns: list[dict] = []

    if llm_fn is None:
        # Offline: no conversation thread (answers are placeholders anyway).
        for q in topic.questions:
            ga = voiced_answer(figure_slug, q, llm_fn=None)
            turns.append({
                "question": q,
                "answer": "[generated at runtime via Claude — run with --live]",
                "grounded_passages": len(ga.grounding.passages),
            })
    else:
        # Live: a real interview. Curated opener, then each subsequent
        # question is generated from the transcript so far, and every answer
        # sees the conversation so it stays a coherent thread.
        history: list[tuple[str, str]] = []
        for i in range(n_questions):
            if i == 0:
                q = topic.questions[0]
            else:
                q = follow_up_question(
                    card, topic.theme, history, llm_fn,
                    is_last=(i == n_questions - 1),
                )
            ga = voiced_answer(figure_slug, q, llm_fn=llm_fn,
                               history=history)
            ans = ga.text or ""
            turns.append({
                "question": q,
                "answer": ans,
                "grounded_passages": len(ga.grounding.passages),
            })
            history.append((q, ans))

    return {
        "figure_slug": figure_slug,
        "figure_name": card.name,
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "theme": topic.theme,
        "news_inspired": topic.news_inspired,
        "news": ({"title": topic.news_title, "url": topic.news_url}
                 if topic.news_inspired else None),
        "cold_open": cold,
        "host_intro": topic.framing,
        "turns": turns,
        "sign_off": (f"That was {card.name}. Thanks for listening — "
                     f"until next time."),
    }


def render_markdown(ep: dict) -> str:
    L = [
        f"# {ep['figure_name']} — podcast episode",
        f"_Generated {ep['generated_at']}_",
        "",
        f"**Theme:** {ep['theme']}",
        "",
    ]
    if ep.get("news_inspired") and ep.get("news"):
        n = ep["news"]
        link = f"[{n['title']}]({n['url']})" if n.get("url") else n["title"]
        L += [f"**Prompted by:** {link}", ""]
    L += ["---", ""]
    if ep["cold_open"]:
        L += [f"> _{ep['cold_open']}_", "", "---", ""]
    L += [f"**HOST:** {ep['host_intro']}", ""]
    for t in ep["turns"]:
        L += [f"**HOST:** {t['question']}",
              "",
              f"**{ep['figure_name'].upper()}:** {t['answer']}",
              "",
              f"<sub>grounded on {t['grounded_passages']} retrieved "
              f"passages</sub>", ""]
    L += ["---", "", f"**HOST:** {ep['sign_off']}"]
    return "\n".join(L)


def write_episode(ep: dict) -> tuple[Path, Path]:
    EPISODES.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now().strftime("%Y%m%d-%H%M")
    base  = EPISODES / f"{ep['figure_slug']}_{stamp}"
    js, md = base.with_suffix(".json"), base.with_suffix(".md")
    js.write_text(json.dumps(ep, indent=2, ensure_ascii=False))
    md.write_text(render_markdown(ep))
    return js, md


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description="Compose a podcast episode.")
    ap.add_argument("--figure", required=True)
    ap.add_argument("--questions", type=int, default=3)
    ap.add_argument("--live", action="store_true",
                    help="Generate real answers via Claude (needs API key).")
    args = ap.parse_args()

    fn = None
    if args.live:
        from consumption.llm import get_llm
        fn = get_llm()

    episode = build_episode(args.figure, llm_fn=fn,
                            n_questions=args.questions)
    js, md = write_episode(episode)
    print(render_markdown(episode))
    print(f"\n— written: {js}\n           {md}")
